modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "${issues_page}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"

# [Customize]
authors = "Me!"
credits = ""

displayURL = "${home_page}"
description = '''
${description}
'''
logoFile = "icon.png"

[[dependencies."${id}"]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${id}"]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "${id}.mixins.json"
